<?php

namespace QuizBot\Database\Seeders;

use Illuminate\Database\Capsule\Manager as Capsule;
use QuizBot\Domain\Model\Achievement;

class AchievementsSeeder
{
    public function seed(): void
    {
        $hasCodeColumn = Capsule::schema()->hasColumn('achievements', 'code');
        $hasPointsColumn = Capsule::schema()->hasColumn('achievements', 'points');
        $hasConditionsColumn = Capsule::schema()->hasColumn('achievements', 'conditions');
        $hasIsActiveColumn = Capsule::schema()->hasColumn('achievements', 'is_active');

        $achievements = [
            // === ДУЭЛИ (15 достижений) ===
            [
                'key' => 'first_duel',
                'title' => 'Первая дуэль',
                'description' => 'Сыграй свою первую дуэль',
                'icon' => '⚔️',
                'rarity' => 'common',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 1,
                'reward_coins' => 50,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 1,
            ],
            [
                'key' => 'first_duel_win',
                'title' => 'Первая победа',
                'description' => 'Одержи первую победу в дуэли',
                'icon' => '🏆',
                'rarity' => 'common',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 1,
                'reward_coins' => 100,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 2,
            ],
            [
                'key' => 'duel_veteran',
                'title' => 'Ветеран дуэлей',
                'description' => 'Сыграй 100 дуэлей',
                'icon' => '🎖️',
                'rarity' => 'rare',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 500,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 3,
            ],
            [
                'key' => 'duel_master',
                'title' => 'Мастер дуэлей',
                'description' => 'Сыграй 500 дуэлей',
                'icon' => '🎯',
                'rarity' => 'epic',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 500,
                'reward_coins' => 2000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 4,
            ],
            [
                'key' => 'win_streak_5',
                'title' => 'Победная серия',
                'description' => '5 побед подряд',
                'icon' => '🔥',
                'rarity' => 'rare',
                'category' => 'duel',
                'condition_type' => 'streak',
                'condition_value' => 5,
                'reward_coins' => 300,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 5,
            ],
            [
                'key' => 'win_streak_10',
                'title' => 'Серийный убийца',
                'description' => '10 побед подряд',
                'icon' => '💥',
                'rarity' => 'epic',
                'category' => 'duel',
                'condition_type' => 'streak',
                'condition_value' => 10,
                'reward_coins' => 1000,
                'reward_gems' => 10,
                'is_secret' => false,
                'sort_order' => 6,
            ],
            [
                'key' => 'win_streak_20',
                'title' => 'Неудержимый',
                'description' => '20 побед подряд',
                'icon' => '👑',
                'rarity' => 'legendary',
                'category' => 'duel',
                'condition_type' => 'streak',
                'condition_value' => 20,
                'reward_coins' => 5000,
                'reward_gems' => 50,
                'is_secret' => false,
                'sort_order' => 7,
            ],
            [
                'key' => 'perfect_duel',
                'title' => 'Идеальная дуэль',
                'description' => 'Ответь на все вопросы правильно (10/10)',
                'icon' => '💯',
                'rarity' => 'rare',
                'category' => 'duel',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 200,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 8,
            ],
            [
                'key' => 'comeback_king',
                'title' => 'Король камбэков',
                'description' => 'Выиграй дуэль после счёта 0:5',
                'icon' => '🦅',
                'rarity' => 'epic',
                'category' => 'duel',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 1500,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 9,
            ],
            [
                'key' => 'duel_wins_50',
                'title' => 'Полсотни побед',
                'description' => '50 побед в дуэлях',
                'icon' => '🏅',
                'rarity' => 'rare',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 50,
                'reward_coins' => 800,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 10,
            ],
            [
                'key' => 'duel_wins_100',
                'title' => 'Сотня побед',
                'description' => '100 побед в дуэлях',
                'icon' => '🥇',
                'rarity' => 'epic',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 2500,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 11,
            ],
            [
                'key' => 'duel_wins_500',
                'title' => 'Чемпион',
                'description' => '500 побед в дуэлях',
                'icon' => '👑',
                'rarity' => 'legendary',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 500,
                'reward_coins' => 10000,
                'reward_gems' => 100,
                'is_secret' => false,
                'sort_order' => 12,
            ],
            [
                'key' => 'underdog',
                'title' => 'Аутсайдер',
                'description' => 'Победи игрока с рейтингом на 500+ выше',
                'icon' => '🐺',
                'rarity' => 'epic',
                'category' => 'duel',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 1000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 13,
            ],
            [
                'key' => 'never_give_up',
                'title' => 'Несгибаемый',
                'description' => 'Проиграй 10 дуэлей, но не сдавайся',
                'icon' => '💪',
                'rarity' => 'rare',
                'category' => 'duel',
                'condition_type' => 'counter',
                'condition_value' => 10,
                'reward_coins' => 500,
                'reward_gems' => 5,
                'is_secret' => false,
                'sort_order' => 14,
            ],
            [
                'key' => 'rematch_winner',
                'title' => 'Реванш',
                'description' => 'Победи игрока, который тебя обыграл',
                'icon' => '🔄',
                'rarity' => 'rare',
                'category' => 'duel',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 300,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 15,
            ],

            // === ВИКТОРИНА (15 достижений) ===
            [
                'key' => 'first_answer',
                'title' => 'Первый ответ',
                'description' => 'Ответь на первый вопрос',
                'icon' => '📝',
                'rarity' => 'common',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 1,
                'reward_coins' => 20,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 16,
            ],
            [
                'key' => 'answers_100',
                'title' => 'Любознательный',
                'description' => 'Ответь на 100 вопросов',
                'icon' => '🤔',
                'rarity' => 'common',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 200,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 17,
            ],
            [
                'key' => 'answers_1000',
                'title' => 'Энциклопедист',
                'description' => 'Ответь на 1000 вопросов',
                'icon' => '📚',
                'rarity' => 'epic',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 1000,
                'reward_coins' => 3000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 18,
            ],
            [
                'key' => 'answers_5000',
                'title' => 'Всезнайка',
                'description' => 'Ответь на 5000 вопросов',
                'icon' => '🧠',
                'rarity' => 'legendary',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 5000,
                'reward_coins' => 15000,
                'reward_gems' => 100,
                'is_secret' => false,
                'sort_order' => 19,
            ],
            [
                'key' => 'correct_100',
                'title' => 'Точность',
                'description' => '100 правильных ответов',
                'icon' => '🎯',
                'rarity' => 'rare',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 500,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 20,
            ],
            [
                'key' => 'correct_1000',
                'title' => 'Эксперт',
                'description' => '1000 правильных ответов',
                'icon' => '🎓',
                'rarity' => 'epic',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 1000,
                'reward_coins' => 3500,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 21,
            ],
            [
                'key' => 'all_categories',
                'title' => 'Универсал',
                'description' => 'Ответь на вопросы во всех категориях',
                'icon' => '🌐',
                'rarity' => 'rare',
                'category' => 'quiz',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 1000,
                'reward_gems' => 10,
                'is_secret' => false,
                'sort_order' => 22,
            ],
            [
                'key' => 'category_master_history',
                'title' => 'Историк',
                'description' => '100 правильных ответов в категории История',
                'icon' => '🏛️',
                'rarity' => 'epic',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 1000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 23,
            ],
            [
                'key' => 'category_master_science',
                'title' => 'Учёный',
                'description' => '100 правильных ответов в категории Наука',
                'icon' => '🔬',
                'rarity' => 'epic',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 1000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 24,
            ],
            [
                'key' => 'category_master_geography',
                'title' => 'Географ',
                'description' => '100 правильных ответов в категории География',
                'icon' => '🌍',
                'rarity' => 'epic',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 1000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 25,
            ],
            [
                'key' => 'speed_answer',
                'title' => 'Молниеносный',
                'description' => 'Ответь правильно за 3 секунды',
                'icon' => '⚡',
                'rarity' => 'rare',
                'category' => 'quiz',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 300,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 26,
            ],
            [
                'key' => 'speed_answers_50',
                'title' => 'Спидраннер',
                'description' => '50 ответов за 3 секунды',
                'icon' => '💨',
                'rarity' => 'epic',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 50,
                'reward_coins' => 1500,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 27,
            ],
            [
                'key' => 'hard_questions_50',
                'title' => 'Любитель сложного',
                'description' => '50 правильных сложных вопросов',
                'icon' => '🔥',
                'rarity' => 'epic',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 50,
                'reward_coins' => 2000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 28,
            ],
            [
                'key' => 'true_or_false_master',
                'title' => 'Мастер интуиции',
                'description' => '100 правильных в Правда/Ложь',
                'icon' => '🎲',
                'rarity' => 'rare',
                'category' => 'quiz',
                'condition_type' => 'counter',
                'condition_value' => 100,
                'reward_coins' => 600,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 29,
            ],
            [
                'key' => 'no_mistakes_10',
                'title' => 'Безупречность',
                'description' => '10 идеальных игр подряд',
                'icon' => '⭐',
                'rarity' => 'legendary',
                'category' => 'quiz',
                'condition_type' => 'special',
                'condition_value' => 10,
                'reward_coins' => 5000,
                'reward_gems' => 50,
                'is_secret' => false,
                'sort_order' => 30,
            ],

            // === МАГАЗИН И РЕСУРСЫ (10 достижений) ===
            [
                'key' => 'first_purchase',
                'title' => 'Первая покупка',
                'description' => 'Купи первый предмет в магазине',
                'icon' => '🛒',
                'rarity' => 'common',
                'category' => 'shop',
                'condition_type' => 'counter',
                'condition_value' => 1,
                'reward_coins' => 50,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 31,
            ],
            [
                'key' => 'shopaholic',
                'title' => 'Шопоголик',
                'description' => 'Купи 50 предметов',
                'icon' => '🛍️',
                'rarity' => 'rare',
                'category' => 'shop',
                'condition_type' => 'counter',
                'condition_value' => 50,
                'reward_coins' => 1000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 32,
            ],
            [
                'key' => 'coins_10000',
                'title' => 'Богач',
                'description' => 'Накопи 10000 монет',
                'icon' => '💰',
                'rarity' => 'rare',
                'category' => 'shop',
                'condition_type' => 'special',
                'condition_value' => 10000,
                'reward_coins' => 0,
                'reward_gems' => 10,
                'is_secret' => false,
                'sort_order' => 33,
            ],
            [
                'key' => 'coins_50000',
                'title' => 'Миллионер',
                'description' => 'Накопи 50000 монет',
                'icon' => '💎',
                'rarity' => 'epic',
                'category' => 'shop',
                'condition_type' => 'special',
                'condition_value' => 50000,
                'reward_coins' => 0,
                'reward_gems' => 50,
                'is_secret' => false,
                'sort_order' => 34,
            ],
            [
                'key' => 'gems_100',
                'title' => 'Коллекционер кристаллов',
                'description' => 'Накопи 100 кристаллов',
                'icon' => '💠',
                'rarity' => 'epic',
                'category' => 'shop',
                'condition_type' => 'special',
                'condition_value' => 100,
                'reward_coins' => 2000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 35,
            ],
            [
                'key' => 'wheel_spin_10',
                'title' => 'Везунчик',
                'description' => 'Крути колесо 10 раз',
                'icon' => '🎡',
                'rarity' => 'rare',
                'category' => 'shop',
                'condition_type' => 'counter',
                'condition_value' => 10,
                'reward_coins' => 500,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 36,
            ],
            [
                'key' => 'wheel_jackpot',
                'title' => 'Джекпот!',
                'description' => 'Выиграй главный приз в колесе',
                'icon' => '🎰',
                'rarity' => 'epic',
                'category' => 'shop',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 1000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 37,
            ],
            [
                'key' => 'lootbox_open_10',
                'title' => 'Открыватель',
                'description' => 'Открой 10 лутбоксов',
                'icon' => '📦',
                'rarity' => 'rare',
                'category' => 'shop',
                'condition_type' => 'counter',
                'condition_value' => 10,
                'reward_coins' => 700,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 38,
            ],
            [
                'key' => 'lootbox_legendary',
                'title' => 'Легендарная удача',
                'description' => 'Получи легендарный предмет из лутбокса',
                'icon' => '✨',
                'rarity' => 'legendary',
                'category' => 'shop',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 3000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 39,
            ],
            [
                'key' => 'all_boosts',
                'title' => 'Коллекция бустов',
                'description' => 'Купи все виды бустов',
                'icon' => '🚀',
                'rarity' => 'epic',
                'category' => 'shop',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 1500,
                'reward_gems' => 15,
                'is_secret' => false,
                'sort_order' => 40,
            ],

            // === СОЦИАЛЬНЫЕ (5 достижений) ===
            [
                'key' => 'invite_friend',
                'title' => 'Пригласи друга',
                'description' => 'Пригласи первого друга',
                'icon' => '👥',
                'rarity' => 'common',
                'category' => 'social',
                'condition_type' => 'counter',
                'condition_value' => 1,
                'reward_coins' => 200,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 41,
            ],
            [
                'key' => 'invite_5_friends',
                'title' => 'Популярный',
                'description' => 'Пригласи 5 друзей',
                'icon' => '🎉',
                'rarity' => 'rare',
                'category' => 'social',
                'condition_type' => 'counter',
                'condition_value' => 5,
                'reward_coins' => 1000,
                'reward_gems' => 10,
                'is_secret' => false,
                'sort_order' => 42,
            ],
            [
                'key' => 'invite_10_friends',
                'title' => 'Магнит друзей',
                'description' => 'Пригласи 10 друзей',
                'icon' => '🤝',
                'rarity' => 'epic',
                'category' => 'social',
                'condition_type' => 'counter',
                'condition_value' => 10,
                'reward_coins' => 2200,
                'reward_gems' => 20,
                'is_secret' => false,
                'sort_order' => 43,
            ],
            [
                'key' => 'invite_25_friends',
                'title' => 'Лидер комьюнити',
                'description' => 'Пригласи 25 друзей',
                'icon' => '👑',
                'rarity' => 'legendary',
                'category' => 'social',
                'condition_type' => 'counter',
                'condition_value' => 25,
                'reward_coins' => 6000,
                'reward_gems' => 60,
                'is_secret' => false,
                'sort_order' => 44,
            ],
            [
                'key' => 'top_10_leaderboard',
                'title' => 'Топ-10',
                'description' => 'Попади в топ-10 рейтинга',
                'icon' => '🏅',
                'rarity' => 'epic',
                'category' => 'social',
                'condition_type' => 'special',
                'condition_value' => 10,
                'reward_coins' => 2000,
                'reward_gems' => 0,
                'is_secret' => false,
                'sort_order' => 45,
            ],
            [
                'key' => 'top_3_leaderboard',
                'title' => 'Подиум',
                'description' => 'Попади в топ-3 рейтинга',
                'icon' => '🥇',
                'rarity' => 'legendary',
                'category' => 'social',
                'condition_type' => 'special',
                'condition_value' => 3,
                'reward_coins' => 5000,
                'reward_gems' => 50,
                'is_secret' => false,
                'sort_order' => 46,
            ],
            [
                'key' => 'rank_1',
                'title' => 'Чемпион мира',
                'description' => 'Стань первым в рейтинге',
                'icon' => '👑',
                'rarity' => 'legendary',
                'category' => 'social',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 10000,
                'reward_gems' => 100,
                'is_secret' => false,
                'sort_order' => 47,
            ],

            // === СЕКРЕТНЫЕ (5 достижений) ===
            [
                'key' => 'secret_night_owl',
                'title' => 'Полуночник',
                'description' => 'Сыграй в 3:00 ночи',
                'icon' => '🦉',
                'rarity' => 'rare',
                'category' => 'special',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 666,
                'reward_gems' => 0,
                'is_secret' => true,
                'sort_order' => 48,
            ],
            [
                'key' => 'secret_lucky_7',
                'title' => 'Счастливая семёрка',
                'description' => 'Накопи ровно 777 монет',
                'icon' => '🍀',
                'rarity' => 'rare',
                'category' => 'special',
                'condition_type' => 'special',
                'condition_value' => 777,
                'reward_coins' => 777,
                'reward_gems' => 0,
                'is_secret' => true,
                'sort_order' => 49,
            ],
            [
                'key' => 'secret_easter_egg',
                'title' => 'Пасхальное яйцо',
                'description' => 'Найди скрытую кнопку',
                'icon' => '🥚',
                'rarity' => 'epic',
                'category' => 'special',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 1337,
                'reward_gems' => 0,
                'is_secret' => true,
                'sort_order' => 50,
            ],
            [
                'key' => 'secret_persistent',
                'title' => 'Упорный',
                'description' => 'Зайди в игру 30 дней подряд',
                'icon' => '📅',
                'rarity' => 'epic',
                'category' => 'special',
                'condition_type' => 'special',
                'condition_value' => 30,
                'reward_coins' => 3000,
                'reward_gems' => 30,
                'is_secret' => true,
                'sort_order' => 51,
            ],
            [
                'key' => 'secret_perfectionist',
                'title' => 'Перфекционист',
                'description' => 'Собери ВСЁ в игре',
                'icon' => '💎',
                'rarity' => 'legendary',
                'category' => 'special',
                'condition_type' => 'special',
                'condition_value' => 1,
                'reward_coins' => 50000,
                'reward_gems' => 500,
                'is_secret' => true,
                'sort_order' => 52,
            ],
        ];

        foreach ($achievements as $achievementData) {
            $payload = $achievementData;

            if ($hasCodeColumn) {
                $payload['code'] = $achievementData['key'];
            }

            if ($hasPointsColumn && !array_key_exists('points', $payload)) {
                $payload['points'] = (int) ($achievementData['reward_coins'] ?? 0);
            }

            if ($hasConditionsColumn && !array_key_exists('conditions', $payload)) {
                $payload['conditions'] = json_encode([
                    'condition_type' => $achievementData['condition_type'] ?? 'counter',
                    'condition_value' => $achievementData['condition_value'] ?? 1,
                ], JSON_UNESCAPED_UNICODE);
            }

            if ($hasIsActiveColumn && !array_key_exists('is_active', $payload)) {
                $payload['is_active'] = true;
            }

            Achievement::updateOrCreate(
                ['key' => $achievementData['key']],
                $payload
            );
        }

        echo "✅ Создано " . count($achievements) . " достижений\n";
    }
}
